// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_content/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_content/flutter_content.dart' as _i4;
import 'package:flutter_content/src/model/model_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IModelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelRepository extends _i1.Mock implements _i2.IModelRepository {
  @override
  _i3.Future<(_i4.CAPIModel?, String?)> getCAPIModel(
          {required String? appName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCAPIModel,
          [],
          {#appName: appName},
        ),
        returnValue: _i3.Future<(_i4.CAPIModel?, String?)>.value((null, null)),
        returnValueForMissingStub:
            _i3.Future<(_i4.CAPIModel?, String?)>.value((null, null)),
      ) as _i3.Future<(_i4.CAPIModel?, String?)>);

  @override
  _i3.Future<void> createOrUpdateModel({required _i4.CAPIModel? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrUpdateModel,
          [],
          {#model: model},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveVote({
    required String? pollName,
    required String? voterId,
    required String? optionId,
    required Map<String, int>? newOptionVoteCountMap,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveVote,
          [],
          {
            #pollName: pollName,
            #voterId: voterId,
            #optionId: optionId,
            #newOptionVoteCountMap: newOptionVoteCountMap,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<
      ({
        Map<String, int>? optionVoteCountMap,
        String? userVotedForOptionId,
        int? when
      })> getPollResultsForUser({
    required String? voterId,
    required String? appName,
    required String? pollName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPollResultsForUser,
          [],
          {
            #voterId: voterId,
            #appName: appName,
            #pollName: pollName,
          },
        ),
        returnValue: _i3.Future<
                ({
                  Map<String, int>? optionVoteCountMap,
                  String? userVotedForOptionId,
                  int? when
                })>.value(
            (optionVoteCountMap: null, userVotedForOptionId: null, when: null)),
        returnValueForMissingStub: _i3.Future<
                ({
                  Map<String, int>? optionVoteCountMap,
                  String? userVotedForOptionId,
                  int? when
                })>.value(
            (optionVoteCountMap: null, userVotedForOptionId: null, when: null)),
      ) as _i3.Future<
          ({
            Map<String, int>? optionVoteCountMap,
            String? userVotedForOptionId,
            int? when
          })>);

  @override
  _i3.Future<Map<String, List<String>>> getVotersByOption({
    required String? appName,
    required String? pollName,
    required List<String>? pollOptionIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVotersByOption,
          [],
          {
            #appName: appName,
            #pollName: pollName,
            #pollOptionIds: pollOptionIds,
          },
        ),
        returnValue: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
        returnValueForMissingStub: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i3.Future<Map<String, List<String>>>);
}
