name: example
description: "Example website project to demo the flutter_content pkg."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.9.7

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.7
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  logging: 1.1.0

#  youtube_player_flutter: ^9.0.3

  #  firebase_core: ^3.3.0
#  firebase_analytics: ^11.2.1
##  firebase_auth: ^5.1.4
#  cloud_firestore: ^5.2.1
#  firebase_storage: ^12.1.3

  flutter_callouts: ^0.2.0

  flutter_content:  ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^5.0.0
  build_runner: ^2.1.11
  built_value_generator: ^8.3.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - startup-scripts/

















