name: example
description: "Example website project to demo the flutter_content pkg."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.9.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

#  flutter_web_plugins:
#    sdk: flutter

  logger: ^2.5.0
  go_router: ^14.6.2
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9

#  youtube_player_flutter: ^9.0.3

  #  firebase_core: ^3.3.0
#  firebase_analytics: ^11.2.1
##  firebase_auth: ^5.1.4
#  cloud_firestore: ^5.2.1
#  firebase_storage: ^12.1.3

  # routing_config_provider:
  #   path: ../../routing_config_provider_pkg

  flutter_content:  #any
    path: ../../flutter_content

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

  flutter_lints: any

flutter:

  uses-material-design: true

  assets:
    - assets/images/
















