name: example
description: "Example website project to demo the flutter_content pkg."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.9.12+18

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_content:
    path: ../
  go_router: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - startup-scripts/












