pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:biancashouse/flutter_content.git
          - cd flutter_content.git
          - git push --mirror git@github.com:biancashouse/flutter_content.git