name: flutter_content
description: Point stuff out for your users => Target, Transform, Configure Callouts, Record to JSON in Dev, and Play in Producton
version: 1.9.1
maintainer: Ian White
homepage: https://github.com/biancashouse/flutter_content
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+flutter_adaptive_scaffold%22
repository: https://github.com/biancashouse/flutter-content
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  #path_provider: ^2.0.11
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  transparent_pointer: ^1.0.1
  dotted_border: ^2.1.0
  image_network: ^2.5.6
  #package_info_plus: ^8.0.0
  #device_info_plus: ^10.1.0
  #universal_platform: ^1.0.0+1
  numeric_keyboard: ^1.1.0
  file_picker: ^8.1.2
  smooth_page_indicator: ^1.2.0+3
  flutter_bloc: ^8.1.6
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.3.1
  firebase_cached_image: ^0.6.0
  firebase_ui_storage: ^2.1.0
  google_fonts: ^6.2.1
  watcher: ^1.1.0
  pointer_interceptor: ^0.10.1+2
  multi_split_view: ^3.5.0
  # compals
  url_launcher: ^6.3.0
  intl: ^0.19.0
  timeago: ^3.7.0
  #flutter_polls: ^0.1.5
  flutter_hooks: ^0.20.5
  calendar_date_picker2: ^1.1.7
  auto_size_text_field: ^2.2.4
  carousel_slider: ^5.0.0
  flutter_fancy_tree_view: ^1.6.0
  webview_flutter: ^4.9.0
#  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.15.0
  webview_flutter_web: ^0.2.3+2
  webview_flutter_platform_interface: ^2.10.0
  percent_indicator: ^4.2.3
  on_screen_ruler: ^0.0.1
  collection: ^1.18.0
  rotated_corner_decoration: ^2.1.0+1
#  _borders: ^1.0.1
#  flutter_inappwebview_web: ^1.0.8
#  youtube_player_iframe: ^5.1.5
#  youtube_parser: ^2.1.3
  flutter_localization: ^0.2.2
  #pretty_json: ^2.0.0
  meta: ^1.15.0
  lorem_ipsum: ^0.0.3
#  firebase_storage_web: ^3.7.3
#  firebase_storage_mocks: ^0.6.1
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+2
  webview_flutter_android: ^4.0.0
  flutter_markdown: ^0.7.3
  gap: ^3.0.1
  go_router: ^14.3.0
  clipboard: ^0.1.3
  flex_color_picker: ^3.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  email_validator: ^3.0.0
#  google_secret_manager: ^1.1.0
  http: ^1.2.2
  image: ^4.2.0
  random_string: ^2.3.1
  vector_math: ^2.1.4
  gradient_borders: ^1.0.1

  routing_config_provider:  ^1.0.0

  bh_shared:  ^2.5.1

  flutter_callouts: ^1.3.0
#    path: ../flutter_callouts_pkg

  logging: ^1.1.0
  dart_mappable: ^4.2.2
  built_value: ^8.9.2
  built_collection: ^5.1.1

#dependency_overrides:
#  web: ^0.5.0 # latest version as of now

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.7
  mockito: ^5.4.4
  text_editor: ^0.7.0
  bloc_test: ^9.1.1
  flutter_lints: any
  build_runner: ^2.1.11
  built_value_generator: ^8.9.2
  dart_mappable_builder: 4.2.2
  json_serializable: ^6.5.3
  analyzer: ^6.7.0

false_secrets:
  - /example/lib/bh-apps.firebase_options.dart

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/images/google-icons/
    - lib/assets/images/carousel-demo/



