// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEevvCbH2OLgFFY43M62wNtvJmgAApUtM',
    appId: '1:646041755699:web:46e4113ead397bdea24346',
    messagingSenderId: '646041755699',
    projectId: 'computer-pals',
    authDomain: 'computer-pals.firebaseapp.com',
    storageBucket: 'computer-pals.appspot.com',
    measurementId: 'G-WST709WM86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmB2RZ-WVobKGfr7hI4mf84TcnbIlpyY',
    appId: '1:646041755699:android:5fd65bd40d42cc9da24346',
    messagingSenderId: '646041755699',
    projectId: 'computer-pals',
    storageBucket: 'computer-pals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMTq10dkUVXwzkWYrA5reHWMuzPLwsMbs',
    appId: '1:646041755699:ios:2b389fac76aa6bf1a24346',
    messagingSenderId: '646041755699',
    projectId: 'computer-pals',
    storageBucket: 'computer-pals.appspot.com',
    iosBundleId: 'com.example.compals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMTq10dkUVXwzkWYrA5reHWMuzPLwsMbs',
    appId: '1:646041755699:ios:c3ccceae3f0443dea24346',
    messagingSenderId: '646041755699',
    projectId: 'computer-pals',
    storageBucket: 'computer-pals.appspot.com',
    iosBundleId: 'com.example.compals.RunnerTests',
  );
}
