name: admin
description: "Example website project to demo the flutter_content pkg."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

#  flutter_web_plugins:
#    sdk: flutter

  logger: ^2.5.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9

  flutter_content:  #any
    path: ../../flutter_content

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

  flutter_lints: any

flutter:

  uses-material-design: true














