name: admin
description: "Example website project to demo the flutter_content pkg."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_content:  #any
    path: ../../flutter_content

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

  flutter_lints: any

flutter:

  uses-material-design: true

false_secrets:
  - /lib/bh-apps.firebase_options.dart













