enum ContentFeature {
  SNIPPET_EDITOR_CALLOUT,
  POPUP_NODE_MENU,
  // POPUP_NODE_PROPERTY_EDITOR,
  POPUP_NODE_TYPE_MENU,
  POPUP_ADD_ACTION_MENU,
  POPUP_MAIN_AXIS_ALIGNMENT_MENU,
  POPUP_MAIN_AXIS_SIZE_MENU,
  POPUP_CROSS_AXIS_ALIGNMENT_MENU,
  POPUP_TEXT_ALIGN_MENU,
  MISSING_NODE_MENU_FOR_FLUTTER_CLASS,
  WRAP_BTN, ADD_CHILD_BTN, INSERT_BEFORE_BTN, INSERT_AFTER_BUTTON,
}
